pluginManagement {
    repositories {
        google()
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = "example-android-app"

// Explicitly include modules so :app tasks can be resolved by classic task selectors.
include(":app")
include(":list")
include(":utilities")
